Rename project to MCP

diff --git a/init/sysv/mcp b/init/sysv/mcp
--- a/init/sysv/mcp
+++ b/init/sysv/mcp
@@ -1,6 +1,6 @@
 #!/bin/sh
 ### BEGIN INIT INFO
-# Provides:          armaadmin
+# Provides:          mcp
 # Required-Start:    $remote_fs
 # Required-Stop:     $remote_fs
 # Default-Start:     2 3 4 5
@@ -11,12 +11,12 @@
 
 case "$1" in
 	start)
-		echo -n "Starting ArmaAdmin: "
-		start-stop-daemon --start --quiet --exec /usr/bin/armaadmin --background --pidfile /var/run/armaadmin.pid --make-pidfile && echo "OK" || echo "Fail"
+		echo -n "Starting MCP: "
+		start-stop-daemon --start --quiet --exec /usr/bin/mcp --background --pidfile /var/run/mcp.pid --make-pidfile && echo "OK" || echo "Fail"
 		;;
 	stop)
-		echo -n "Stopping ArmaAdmin: "
-		start-stop-daemon --stop --quiet --pidfile /var/run/armaadmin.pid && echo "OK" || echo "Fail"
+		echo -n "Stopping MCP: "
+		start-stop-daemon --stop --quiet --pidfile /var/run/mcp.pid && echo "OK" || echo "Fail"
 		;;
 	restart)
 		"$0" stop
